# Generated by Django 5.2.6 on 2025-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_productmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='remainder',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
